### PR TITLE
Jekyll Layout

### LINKED ISSUE #12: Use Jekyll layout for shared elements
Trying to keep the header and footer in sync between changes is slightly annoying, and will only become more annoying if/when more pages are added. Since you're hosting on GitHub Pages, it would be fairly simple to pull the shared elements out into a Jekyll layout to keep them in one place.

I'm happy to tackle that for you (and add instructions to the README for local development) if you'd like.

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #12.

### CODE REVIEW

**Comment by cassidyjames** [comment]
An artificially large diff since it involved splitting up existing files into smaller ones.

**Comment by hughsie** [comment]
I'm really wondering if it might be easier to convert this to Flask+bootstrap, which gives us the ability to do cleverer things in the future and means I don't need to learn Yet Another Framework...

**Comment by cassidyjames** [comment]
What I like about Jekyll is that it's stupid simple (just some handy static generation helpers), and supported natively by GitHub Pages. And you're already technically using it in OARS, just not extensively. 😉 But ultimately it's up to you. I've never heard of Flask.

**Comment by Calinou** [comment]
What's the status on this? I'd like to contribute some changes but would prefer avoiding conflicts if this merged :slightly_smiling_face:

**Comment by cassidyjames** [comment]
@Calinou if @hughsie doesn't want to use Jekyll than this should be closed, sorry.

**Comment by cassidyjames** [comment]
@hughsie would you be open to reconsidering this? Jekyll is extremely straightforward and is less of a "framework" and is more just a simple static site generator that allows easy templating. Pretty much any time I want to contribute a change to the OARS generator I'm scared away by the giant single page HTML with lots of repetition everywhere, and something like Jekyll would be much easier to contribute to. Plus, it generates a static site and thus the end result can be identical to what's there now, just easier to work with.

**Comment by hughsie** [comment]
> Jekyll is extremely straightforward

Maybe; the KISS of now does somewhat appeal...

**Pull request closed without merging**
