### PR TITLE
Index: Update copyright date

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by hughsie** [comment]
Can we just remove the end year completely? Otherwise it's just going to get bumped every year :)

**Comment by AsciiWolf** [comment]
To be honest, I am not sure if that's a good idea. 2015 was a long time ago and website with such copyright date will probably look a little bit outdated. :) But it's of course up to you.

**Comment by AsciiWolf** [comment]
Or maybe remove the copyright date entirely? The date is already stated in the header of these html files, just under the DOCTYPE definition.

**Comment by ChildishGiant** [comment]
You can leave it the year you made it (you don't need claim copyright in the first place you are entitled to it by default), or put `2015 - present` or not include a year at all. More info: https://hynek.me/til/copyright-years/

**Comment by AsciiWolf** [comment]
> You can leave it the year you made it (you don't need claim copyright in the first place you are entitled to it by default), or put `2015 - present` or not include a year at all. More info: https://hynek.me/til/copyright-years/

Sounds good, thanks! I have updated the PR.

**Comment by AsciiWolf** [comment]
@hughsie Please re-review. :-)

**Review by hughsie — APPROVED** [review]

**Pull request merged**
