### PR TITLE
Add Projects using OARS

### LINKED ISSUE #9: Add list of projects implementing OARS
It might lend more confidence in OARS if we list projects that are using it, like GNOME Software, elementary AppCenter, and anyone else. This could be as simple as adding it to the homepage for now (unless/until it gets large enough to warrant its own page).

### PR DESCRIPTION
**Pull request by cassidyjames**
WIP, but adding here for critique. elementary AppCenter would actually need to be removed since we're not doing anything with OARS yet, but included for now for visualization.

image

To-do:
- [x] Decide if this is visually too heavy
- [x] Ship icons in this codebase so we're not relying on RawGit?
- [x] Remove AppCenter for now
- [x] Decide on an ordering
- [ ] Figure out if there are other projects to add

Fixes #9 if merged

### CODE REVIEW

**Comment by danirabbit** [comment]
Does FlatPak actually mandate OARS data as opposed to FlatHub?

I really like the call to action there to include your project. Good call.

**Comment by cassidyjames** [comment]
Ah, yeah I think I got those mixed up! Corrected in the latest commit.

**Comment by hughsie** [comment]
I think this is nice. I do think we need to ship the icons ourselves tho. I don't think the ordering matters too much; although "date of adoption" or "number of users" seems like a good metric.

**Comment by cassidyjames** [comment]
Yeah I was planning on alphabetical naively, but date of adoption might be more meaningful plus easily measurable. Number of users is going to be hard to measure for many projects.

**Comment by hughsie** [comment]
I'm not sure it matters that much. Project over ego and all that.

**Comment by Conan-Kudo** [comment]
I'd suggest centering the `Your Project` icon and making sure it's always on its own row. That makes it more visually distinct and easier to notice.

**Comment by cassidyjames** [comment]
@Conan-Kudo I disagree since the number of items is variable. Being the last one is a nice ending call-to-action for those who might be looking for a project they're involved with in the list.

**Comment by cassidyjames** [comment]
I've addressed all but the last TODO: figure out if there are other projects. Other than that, it's ready to review. Current state:

oars

**Comment by hughsie** [comment]
Looks good to me, can you rebase and squash down and force push the branch please, then LGTM.

**Comment by cassidyjames** [comment]
@hughsie rebased and squashed

**Comment by mmstick** [comment]
@hughsie Just a reminder that GitHub's UI provides a **Squash and merge** and **Rebase and merge** button alongside **Merge** so that you can do it from your end without needing to request that a contributor does it on their end (time-consuming).

**Comment by Conan-Kudo** [comment]
@cassidyjames @mmstick I don't think that's what he was asking for. I think he was asking for some care in the commit message, to make a meaningful set of changes.

The current squashed commit is awful (and is basically the kind of commit message that GitHub generates...).

**Comment by mmstick** [comment]
@Conan-Kudo GitHub does let you modify the commit message for the resulting squashed / merged commit, however. Easily done from a maintainer's point of view (if they understand what they are merging).

**Pull request merged**
