### PR TITLE
Bump copyright date

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by hughsie** [comment]
Nah, I think the opposite -- i.e. remove the larger date. The legal consensus is that only the start year is important.

**Comment by AsciiWolf** [comment]
I am not sure I agree here. The larger date is an important indicator showing that the project development is still alive (or at least when the project got updated). But this is of course up to you, I can remove the larger date if you want.

**Comment by hughsie** [comment]
Okay, compromise -- I do see your point. Remove the ones in the comment section and update the ones in the visible section?

**Comment by AsciiWolf** [comment]
Done. :-)

**Pull request merged**
